### ISSUE TITLE
Bot don't render anymore.

### ISSUE THREAD

**Issue by Caaruzo** [Aphris-Karu/corrade-docker#1]
**Which Docker Container are you having an issue with**
Corrade-continuous

**Describe the bug**
Bots don't render anymore in SL. And stay a cloud.

WAS told me in discord, verison 10 is legacy now, and the render problem was fixed in 11.0.79.64 and above.
Is there any update for the docker image to the latest corrade versions pls?

Thx much

**Comment by Aphris-Karu** [comment]
Thank you for letting me know. It looks like the author of corrade made some changes to the site that broke the automated builds. I have fixed the automatons and version 11 is now up on docker hub.
