### ISSUE TITLE
entrypoint not found

### ISSUE THREAD

**Issue by myggenresident** [Aphris-Karu/corrade-docker#2]
Following the instructions on https://hub.docker.com/r/aphris/corrade-release stops at step #2 (docker run) because the defined entrypoint does not exist in the container.

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/corrade/start.sh": stat /corrade/start.sh: no such file or directory: unknown.
```

**Comment by Aphris-Karu** [comment]
Try it now. There was an issue with the automatic builds and the changes to the authors website.
